---

- name: Ensure secrets dir exists
  file:
    path: "{{ playbook_dir }}/{{ item.value.directory }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_secrets_username }}"
    group: "{{ ansible_secrets_groupname }}"
  with_dict: "{{ ansible_secrets_list }}"