---

    - name: Copy config file {{ item.value.file }} from {{ item.value.url }} to {{ playbook_dir }}/{{ item.value.directory }}/{{ item.value.file }}
      s3:
        bucket: "{{ item.value.bucket }}"
        object: "{{ item.value.source }}"
        dest: "{{ playbook_dir }}/{{ item.value.directory }}/{{ item.value.file }}"
        mode: get
        overwrite: different
      register: result
      with_dict: "{{ ansible_secrets_dict }}"
