---

- name: Ensure secrets dir exists
  file:
    path: "{{ ansible_secrets_directory }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_secrets_username }}"
    group: "{{ ansible_secrets_groupname }}"