---

- name: Make sure there is no existing file called {{ ansible_secrets_directory }}/{{ ansible_secrets_file }}
  file:
    path: "{{ ansible_secrets_directory }}/{{ ansible_secrets_file }}"
    state: absent


- name: Copy config file {{ ansible_secrets_file }} from {{ ansible_secrets_s3_url }} to {{ ansible_secrets_directory }}/{{ ansible_secrets_file }}
  command: "{{ ansible_aws_paths.aws }} s3 cp {{ ansible_secrets_s3_url }} {{ ansible_secrets_directory }}/{{ ansible_secrets_file }}"
  register: result

- name: Check if the file exists
  stat:
    path: "{{ ansible_secrets_directory }}/{{ ansible_secrets_file }}"
  register: ansible_secrets_file_info


- name: Fail if {{ ansible_secrets_directory }}/{{ ansible_secrets_file }} file doesn't exist
  fail: msg="{{ ansible_secrets_directory }}/{{ ansible_secrets_file }} file doesn't exist"
  when: not ansible_secrets_file_info.stat.exists





